apis/urls.py
from django.urls import include, path
# import routers
from rest_framework import routers

# import everything from views
from .views import (
    UserViewSet,
    DataItemViewSet,
    RealDataItemViewSet,
    RealDataEntryViewSet,
    DiscreteDataItemViewSet,
    DiscreteDataEntryViewSet,
    TopicViewSet,
    DeviceViewSet,
    DeviceTypeViewSet,
    ServerViewSet,
    RestServerViewSet,
    MqttBrokerViewSet,
    FunctionViewSet,
    CommandViewSet,
    function_value,
    )

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'data_items', DataItemViewSet)
router.register(r'real_data_items', RealDataItemViewSet)
router.register(r'real_data_entries', RealDataEntryViewSet)
router.register(r'discrete_data_items', DiscreteDataItemViewSet)
router.register(r'discrete_data_entries', DiscreteDataEntryViewSet)
router.register(r'mqtt_brokers', MqttBrokerViewSet)
router.register(r'devices', DeviceViewSet)
router.register(r'device_types', DeviceTypeViewSet)
router.register(r'topics', TopicViewSet)
router.register(r'servers', ServerViewSet)
router.register(r'rest_servers', RestServerViewSet)
router.register(r'functions', FunctionViewSet)
router.register(r'commands', CommandViewSet)

urlpatterns = [
    path('', include(router.urls), name='apis'),
    path('api-auth/', include('rest_framework.urls')),
    path('function/<int:function_id>/value/', function_value, name='function_value')

]

automation/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from automation.views import FunctionListView
urlpatterns = [
    path('dashboard/', TemplateView.as_view(template_name="automation/dashboard.html"), name="dashboard   "),
    path('dashboard/functions/', FunctionListView.as_view(template_name="automation/functions.html"), name="functions"),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('apis/', include('apis.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('automation/', include('automation.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

automation/models.py
from django.db import models
from command.models import Function, Device


class Server(models.Model):
    class ServerTypes(models.TextChoices):
        MQTT = 'MQTT', 'mqtt'
        REST = 'REST', 'rest'
    name = models.CharField(max_length=50)
    ip_address = models.GenericIPAddressField()
    server_type = models.CharField(choices=ServerTypes.choices, default=ServerTypes.MQTT)

    def __str__(self):
        return self.name


class RestServer(Server):
    class HostProtocols(models.TextChoices):
        HTTP = 'HTTP', 'http'
        HTTPS = 'HTTPS', 'https'
    protocol = models.CharField(choices=HostProtocols.choices, default=HostProtocols.HTTP)
    host = models.CharField(max_length=100)
    port = models.IntegerField(default=80)
    path = models.CharField(max_length=25, default='/apis')
    username = models.CharField(max_length=50, null=True, blank=True)
    password = models.CharField(max_length=50, null=True, blank=True)


class MqttBroker(Server):
    class HostProtocols(models.TextChoices):
        MQTT = 'MQTT', 'mqtt'
        MQTTS = 'MQTTS', 'mqtts'
        WS = 'WS', 'ws'
        WSS = 'WSS', 'ws'
    protocol = models.CharField(choices=HostProtocols.choices, default=HostProtocols.MQTTS)
    host = models.CharField(max_length=100)
    port = models.IntegerField(default=8883)
    path = models.CharField(max_length=25, default='/mqtt')
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    ssl = models.BooleanField(default=True)


class Topic(models.Model):
    name = models.CharField(max_length=50)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    device = models.OneToOneField(Device, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    def get_name(self):
        return self.name + str(self.device.device_id)


class DataGroup(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class ScalingMixin(models.Model):
    raw_lo = models.FloatField(default=0.0)
    raw_hi = models.FloatField(default=100.0)
    scale_lo = models.FloatField(default=0.0)
    scale_hi = models.FloatField(default=100.0)
    scaling_on = models.BooleanField(default=False)

    class Meta:
        abstract = True

    def get_value(self, raw_value):
        if self.scaling_on:
            raw_range = self.raw_hi - self.raw_lo
            scale_range = self.scale_hi - self.scale_lo
            return scale_range/raw_range * (raw_value - self.raw_lo) + self.scale_lo
        else:
            return raw_value


class LoggingMixin(models.Model):
    logging_on = models.BooleanField(default=False)

    class Meta:
        abstract = True


class AnalogLoggingMixin(LoggingMixin):
    logging_deadband = models.FloatField(default=1.0, null=True)

    class Meta:
        abstract = True


class FunctionAssigner(models.Model):
    class ReadWrite(models.IntegerChoices):
        NONE = 0
        READ = 1
        WRITE = 2
        READ_WRITE = 3

    class AssignerClassName(models.TextChoices):
        COMPUTER_DEVICE = 'COMPUTER DEVICE', 'ComputerFunctionAssigner'
        PLC = 'PLC', 'PLCFunctionAssigner'
    # data_item = models.ForeignKey(DataItem, null=True)
    type = models.CharField(max_length=50, choices=AssignerClassName.choices)
    read_write = models.IntegerField(default=ReadWrite.NONE, choices=ReadWrite.choices)

    def permit_read(self):
        return True if self.read_write in [self.ReadWrite.READ, self.ReadWrite.READ_WRITE] else False

    def permit_write(self):
        return True if self.read_write in [self.ReadWrite.WRITE, self.ReadWrite.READ_WRITE] else False


class ComputerFunctionAssigner(FunctionAssigner):

    function_read = models.ForeignKey(Function, related_name='read_functions', null=True, on_delete=models.SET_NULL)
    function_write = models.ForeignKey(Function, related_name='write_functions', null=True, on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        self.type = FunctionAssigner.AssignerClassName.COMPUTER_DEVICE
        super(ComputerFunctionAssigner, self).save(*args, **kwargs)

    def config_check(self):
        if self.permit_read() and self.function_read is None:
            raise Exception("There is no function assigned for reading this DataItem.")
            return False
        if self.permit_write() and self.function_write is None:
            raise Exception('There is no function assigned for writing this DataItem')
            return False
        return True


class DataItem(models.Model):
    class Type(models.TextChoices):
        STRING = 'STRING', 'string'
        DISCRETE = 'DISCRETE', 'discrete'
        INT = 'INT', 'integer'
        REAL = 'REAL', 'real'

    name = models.CharField(max_length=100, unique=True)
    topic = models.ForeignKey(Topic, null=True, on_delete=models.SET_NULL)
    data_group = models.ManyToManyField(DataGroup, blank=True)
    data_type = models.CharField(max_length=10, choices=Type.choices)
    alarm_enable = models.BooleanField(default=False)
    alarm_status = models.BooleanField(default=False)
    function_assigner = models.OneToOneField(FunctionAssigner, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    def permit_read(self, read_write):
        if self.function_assigner:
            if read_write == self.function_assigner.ReadWrite.READ:
                return self.function_assigner.permit_read()
            return self.function_assigner.permit_write()
        raise Exception('The function assigner has not been defined for this Data Item.')


class StringDataItem(LoggingMixin, DataItem):
    alarm_string = models.CharField(max_length=100)


class DiscreteDataItem(LoggingMixin, DataItem):
    class AlarmState(models.TextChoices):
        TRUE = 'TRUE', 'true'
        FALSE = 'FALSE', 'false'
        NONE = 'NONE', 'none'


class IntegerDataItem(ScalingMixin, LoggingMixin, DataItem):
    pass


class RealDataItem(ScalingMixin, AnalogLoggingMixin, DataItem):
    decimal_places = models.IntegerField(default=2)


class DataEntry(models.Model):
    data_item = models.ForeignKey(DataItem, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)


class StringDataEntry(DataEntry):
    value = models.CharField(max_length=1024)


class DiscreteDataEntry(DataEntry):
    value = models.BooleanField(default=False)


class IntegerDataEntry(DataEntry):
    value_raw = models.IntegerField(null=True)
    value = models.IntegerField(null=True)


class RealDataEntry(DataEntry):
    value_raw = models.FloatField(null=True)
    value = models.FloatField(null=True)

command/models.py
from django.db import models
import uuid


# Create your models here.


class DeviceType(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Device(models.Model):
    name = models.CharField(max_length=50, unique=True)
    device_id = models.UUIDField(default=uuid.uuid4)
    device_type = models.ForeignKey(DeviceType, on_delete=models.CASCADE, null=True)
    is_itself = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if (self.is_itself and not Device.objects.filter(is_itself=True).exists()) or not self.is_itself or self.id:
            super().save(*args, **kwargs)
        else:
            raise Exception("A Device already exists that is a reference to itself.  Device was not saved.")

        def create_func(name, read_write):
            func = Function()
            func.name = name
            func.read_write = read_write
            func.active = True
            func.args = []
            func.remote = True
            func.asyncro = False
            func.device = self
            func.save()
        if self.functions.filter(name='read_functions', device=self).count() == 0:
            create_func('read_functions', Function.ReadWriteChoices.READ)


class Function(models.Model):

    class ReadWriteChoices(models.IntegerChoices):
        NONE = 0
        READ = 1
        WRITE = 2
    name = models.CharField(max_length=100)
    args = models.JSONField(default=[], blank=True)  # Dictionary of the args and kwargs
    device = models.ForeignKey(Device, on_delete=models.CASCADE, null=True, blank=True, related_name='functions')
    remote = models.BooleanField(default=False)
    asyncro = models.BooleanField(default=False)
    response_timeout = models.IntegerField(default=10)
    active = models.BooleanField(default=True)
    read_write = models.IntegerField(default=ReadWriteChoices.NONE, choices=ReadWriteChoices.choices)
    value = 'not queried'

    class Meta:
        unique_together = ('name', 'device')

    def __str__(self):
        return str(self.device) + ' : ' + self.name

    def save(self, *args, **kwargs):
        # self.full_clean()
        if self.args is None:
            self.args = []
        super(Function, self).save(*args, **kwargs)


class ScheduledCommand(models.Model):
    function = models.ForeignKey(Function, on_delete=models.CASCADE)
    args = models.JSONField(null=models.CASCADE)
    asyncro = models.BooleanField(default=False)
    job_id = models.UUIDField(default=uuid.uuid4)
    interval_number = models.IntegerField(default=1)
    interval = models.CharField(max_length=20)
    at = models.CharField(max_length=5, null=True)
    run_once = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def run(self):
        cmd = Command()
        cmd.function = self.function
        cmd.args = self.args
        cmd.asyncro = self.asyncro
        cmd.schedule = self
        cmd.run()


class Command(models.Model):
    function = models.ForeignKey(Function, on_delete=models.CASCADE)
    schedule = models.ForeignKey(ScheduledCommand, on_delete=models.CASCADE, null=True)
    args = models.JSONField(null=True)  # Dictionary of the values of args
    executed = models.BooleanField(default=False)
    start = models.DateTimeField(null=True)
    end = models.DateTimeField(null=True)
    return_message = models.JSONField(null=True)
    # asyncro = models.BooleanField(default=False)

automation/views.py
from django.views.generic.list import ListView
from command.models import Function


class FunctionListView(ListView):
    queryset = Function.objects.filter(active=True).order_by('device', 'read_write')

templates/automation/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap_icons%}
<!-- Alerts -->
{% include 'partials/_alerts.html' %}
<style media="screen">
  .center {
  margin: auto;
  width: 80%;
  padding: 10px;
</style>
<div class="offcanvas offcanvas-start w-25" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">
    <div class="offcanvas-header">
        <h6 class="offcanvas-title d-none d-sm-block" id="offcanvas">Menu</h6>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body px-0">
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
            <li class="nav-item">
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                </a>
            </li>
            <li>
                <a href="#submenu1" data-bs-toggle="collapse" class="nav-link text-truncate">
                    <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
            </li>
            <li>
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Orders</span></a>
            </li>
            <li class="dropdown">
                <a href="#" class="nav-link dropdown-toggle  text-truncate" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fs-5 bi-bootstrap"></i><span class="ms-1 d-none d-sm-inline">Bootstrap</span>
                </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </li>
            <li>
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">Products</span></a>
            </li>
            <li>
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Customers</span> </a>
            </li>
        </ul>
    </div>
</div>
<div class="container-fluid center">
  <!-- toggler -->
  <button class="btn float-start" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">

      {% bs_icon 'menu-down' %}
  </button>
    <div class="row">
        <div class="col min-vh-100 p-4">
            {% block sub_content %} {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

templates/automation/functions.html
{% extends 'automation/dashboard.html' %}
{% block sub_content %}
<script type="text/javascript">
  $(document).ready(function(){
    {% regroup object_list by device as device_list %}
    {% for d in device_list%}
        {% for function in d.list %}
        $("#{{function.id}}_button").on('click', function(){
          //print(event.data.id)
          getValue({{ function.id }});
        })
        {% endfor %}
    {% endfor %}
    function getValue(function_id) {
      var args=[];
      $("input[name='" + function_id + "_args']").each(function(){
        console.log("arg " + $(this).val());
        args.push($(this).val());
        //console.log(args);
      })
      $('#'+function_id + '_value').val('waiting');
      //console.log("Here are the args " + $("input[name='" + function_id + "_args']").val());
      $.ajax({
        url: "http://{{ request.get_host }}/apis/function/" + function_id + "/value/",
        type: "GET",
        data: {args: args, var1:"hello"},
        dataType: 'json',
        success: function(res) {
          console.log(res);
          $('#' + function_id + '_value').val(res.ret_value);
        }
      })
    }


  })




</script>
<style media="screen">
</style>
<section id="bc" class="mt-3 center">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">
            <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active"> Dashboard</li>
      </ol>
    </nav>
  </div>
</section>

<section id="functions" class="py-4 center">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% regroup object_list by device as device_list %}
        <ul>

          {% for device in device_list %}

          <li>{{ device.grouper }}
            <ul>
              {% for function in device.list %}
              <li> {{function.name}}, Arguments,

                {% for arg in function.args %}
                  {{ arg }}: <input type="text" name="{{ function.id}}_args">
                {% endfor %}
                <input id="{{function.id}}_value" type="text" name="" value="{{function.value}}">
                {% if function.read_write == 1 %}
                <button class='button' id="{{ function.id }}_button">Read</button>

                {% elif function.read_write == 2 %}
                <button class='button' id="{{ function.id }}_button">Write</button>
                {% else %}
                <button class='button' id="{{ function.id }}_button">Run</button>
                {% endif %}
              </li>
              {% endfor %}
            </ul>
          </li>
          {% endfor %}
        </ul>


      </div>
    </div>
  </div>
</section>
{% endblock %}